### ISSUE TITLE
Exception in logging method (when an input file is not found?)

### ISSUE THREAD

**Issue by jlumbroso** [josephlou5/roseingrave#26]
We encountered a terminating exception from the logging method:

![Screenshot 2023-07-09 at 1 22 59 PM](https://github.com/scarlatti/roseingrave/assets/11770469/46662831-de81-4f65-8ba6-0376a842af6a)

This is the repository at the state that it was in when we ran the command:
https://github.com/scarlatti/argos-muenster/tree/c52e13d3c8a28a8a3de3267c11d6181fcc92f0f8

The command that we ran was:
```shell
pipenv run roseingrave create_sheet -r -vd input/volunteer_definitions.json
```
It is possible that this is a simple path error, but at any rate, the error reporting is failing.

This seems to be the relevant code snippet before failure:
https://github.com/scarlatti/roseingrave/blob/f4e7e9e003185aac8a19d3c058b64bc0ef68d2a2/src/roseingrave/_output_files.py#L69-L79

**Comment by jlumbroso** [comment]
We found the issue, it was related to the existing `output/spreadsheets.json` file that was empty.

This file was empty because @jaspervanderklis manually erased its content to reset the process. We realize that if he had deleted the file, this error would not have presented, as the file would just have been regenerated.

Still, it would be better for this to lead to an error message (or even to bypass), rather than silently failing.

**Comment by josephlou5** [comment]
This specific error ("Expecting value: line 1 column 1 (chat 0)") happens when `json.loads()` tries to parse an empty string, which is not valid JSON. It seems to me that the spreadsheets index file must have been empty when this was run. (Note that the file not existing is already handled specially.)

**Comment by jlumbroso** [comment]
I think "Expecting value: xxx" is not a proper user-facing message. Someone that is not a programmer would not really know how to deal with this scenario. For now, I am supervising the use of Roseingrave, but hopefully it can be used without us in the loop. So it's important that the output of the command be self-explainable.

I can understand that there is a problem loading something, but beyond that, it is not clear.

Here, ideally, I think there are two things that are missing:
- that the error is in **parsing the JSON** (as opposed to "finding the file" [i.e., file doesn't exist or is in a forbidden tree], or "opening the file" [i.e., not sufficient permissions, or not enough memory or sporadic error]);
- what is the specific name of the file name (identifying the files by their description, i.e., "Reading spreadsheet index file" is useful when providing a status; but when there's an error, the non-ambiguity of a file path is comforting!).

I think that if at least the message could mention JSON, that could be helpful.

In terms of encapsulation, since the `read_json` method reads the JSON file, the problem could be dealt there, as in convert a JSON error into a ValueError that has a message stating the problem is in parsing the JSON file — maybe that specific error can be recognized as the file being empty.

Otherwise, there could be an `except JSONDecodeError` in `read_spreadsheets_index`.

**Comment by josephlou5** [comment]
The current behavior of encountering an empty file with commit 52d14fe80f8318d6570515fab8ad7fdd353c9e1b is to fail with an error. There are only a few cases where an empty JSON file can be ignored and a default used instead, but being able to detect that case might involve more complicated code. I think for now the solution of failing with an error that the file is empty is sufficient enough, since the user can simply just delete the file and try again.
