### ISSUE TITLE
Character encoding issue when exporting data from Google Spreadsheets

### ISSUE THREAD

**Issue by jlumbroso** [josephlou5/roseingrave#28]
As I was doing `roseingrave volunteer_summary`, I was confronted with the following issue:

![Screenshot 2023-08-06 at 12 02 40 PM](https://github.com/scarlatti/roseingrave/assets/11770469/597fe305-ca98-4e88-bb48-8baeceb55a3e)

The sheet "K.12" did not export because of some sort of error, and resulted in none of the "K.12" data being in the corresponding volunteer's data export, `fimteinfo@gmail.com.json`.

Steps to reproduce:
- Clone `https://github.com/scarlatti/argos-cary` (private repo)
- Log-in to Google Auth
- Run `pipenv run roseingrave volunteer_summary`

Here's an example of just the K.12 sheet to manually take a look:
https://docs.google.com/spreadsheets/d/1oQa3toeBQ8CnD0fYw-MUPo28A6K66G08e-cXSLWNOYQ/edit?usp=sharing

**Comment by josephlou5** [comment]
@jlumbroso It looks like the issue is because cell A1 has been replaced with `"2"`. However, the command expects A1 to contain a piece name with a link. The actual error occurred when attempting to call `re.Pattern.match()` with a non-string or non-bytes-like object (when attempting to parse the hyperlink for the piece name). Additional checks can be added to handle this, but in this case the problem was an invalid sheet.

On that note, I'm not sure how cell A1 was able to be edited, since the protection permissions should only include the owner (unless this spreadsheet was generated before that update).
